# Root input variables.
#
# Only `region` is required; everything else defaults so a bare
# `terraform plan -var-file=tfvars/us-east-1.tfvars` works.
#
# Note what is NOT here:
#
#   - No `env` variable. One set of tables serves both dev and prod, which are
#     separated at the Kubernetes namespace layer (see main.tf).
#   - No `deepgram_api_key` or any other secret. Secrets go into the Kubernetes
#     Secret out-of-band; putting one in tfvars would land it in state, and state
#     is not a secret store.

variable "region" {
  description = "AWS region to deploy into. Must match the selected workspace name."
  type        = string
}

variable "owner" {
  description = <<-EOT
    Resource-name prefix and the Owner tag value. The course AWS account is shared,
    so this is what keeps Recall's tables and bucket from colliding with another
    student's. Changing it renames every resource, which DynamoDB cannot do
    in place — a rename destroys and recreates the tables, losing all data.
  EOT
  type        = string
  default     = "shahdra"
}

# --- DynamoDB table names ---------------------------------------------------
#
# These default to the bare names the application code itself defaults to
# (services/study-mcp/app.py:63-72), so the services work with no env vars set at
# all in local development. In the cluster the ConfigMap sets them explicitly to
# the prefixed names this Terraform actually creates.
#
# They are variables rather than hard-coded so a second isolated stack (a
# throwaway environment, a load test) needs no code change.

variable "cards_table_name" {
  description = "DynamoDB table holding flashcards and their SM-2 state."
  type        = string
  default     = "Cards"
}

variable "decks_table_name" {
  description = "DynamoDB table holding decks (one per uploaded material)."
  type        = string
  default     = "Decks"
}

variable "profile_table_name" {
  description = "DynamoDB table holding the long-term learner profile."
  type        = string
  default     = "LearnerProfile"
}

variable "table_name_prefix" {
  description = <<-EOT
    Prefix applied to all three table names, e.g. "shahdra-recall-". Set to "" to
    use the bare names. Prefixed by default because the account is shared and
    "Cards" is exactly the sort of name another project would also pick.
  EOT
  type        = string
  default     = "shahdra-recall-"
}

# --- S3 --------------------------------------------------------------------

variable "uploads_retention_days" {
  description = <<-EOT
    Days before an uploaded PDF/text file is expired from S3. The cards generated
    from a file live in DynamoDB and are unaffected — this only reclaims the raw
    source material, which is never read again after ingestion.
  EOT
  type        = number
  default     = 90
}

# --- DynamoDB durability ---------------------------------------------------

variable "point_in_time_recovery" {
  description = <<-EOT
    Enable DynamoDB point-in-time recovery on all three tables. Off by default:
    PITR bills for continuous backups, and this is a course project whose data can
    be regenerated by re-uploading material. Turn it on if a demo's review history
    becomes worth protecting.
  EOT
  type        = bool
  default     = false
}
