# Root input variables.
#
# Only `region` is required; everything else defaults so a bare
# `terraform plan -var-file=tfvars/us-east-1.tfvars` works.
#
# Note what is NOT here:
#
#   - No `env` variable. One set of tables and ONE cluster serve both dev and prod,
#     which are separated at the Kubernetes namespace layer (see main.tf).
#   - No `deepgram_api_key` or any other secret. Secrets go into the Kubernetes
#     Secret out-of-band; putting one in tfvars would land it in state, and state
#     is not a secret store.
#   - No `ami_id`. Hard-coding an AMI pins the config to one region; the Ubuntu
#     22.04 image is looked up per-region by a data source in the cluster module.

variable "region" {
  description = "AWS region to deploy into. Must match the selected workspace name."
  type        = string
}

variable "owner" {
  description = <<-EOT
    Resource-name prefix and the Owner tag value. The course AWS account is shared,
    so this is what keeps Recall's tables and bucket from colliding with another
    student's. Changing it renames every resource, which DynamoDB cannot do
    in place — a rename destroys and recreates the tables, losing all data.
  EOT
  type        = string
  default     = "shahdra"
}

# --- DynamoDB table names ---------------------------------------------------
#
# These default to the bare names the application code itself defaults to
# (services/study-mcp/app.py:63-72), so the services work with no env vars set at
# all in local development. In the cluster the ConfigMap sets them explicitly to
# the prefixed names this Terraform actually creates.
#
# They are variables rather than hard-coded so a second isolated stack (a
# throwaway environment, a load test) needs no code change.

variable "cards_table_name" {
  description = "DynamoDB table holding flashcards and their SM-2 state."
  type        = string
  default     = "Cards"
}

variable "decks_table_name" {
  description = "DynamoDB table holding decks (one per uploaded material)."
  type        = string
  default     = "Decks"
}

variable "profile_table_name" {
  description = "DynamoDB table holding the long-term learner profile."
  type        = string
  default     = "LearnerProfile"
}

variable "table_name_prefix" {
  description = <<-EOT
    Prefix applied to all three table names, e.g. "shahdra-recall-". Set to "" to
    use the bare names. Prefixed by default because the account is shared and
    "Cards" is exactly the sort of name another project would also pick.
  EOT
  type        = string
  default     = "shahdra-recall-"
}

# --- S3 --------------------------------------------------------------------

variable "uploads_retention_days" {
  description = <<-EOT
    Days before an uploaded PDF/text file is expired from S3. The cards generated
    from a file live in DynamoDB and are unaffected — this only reclaims the raw
    source material, which is never read again after ingestion.
  EOT
  type        = number
  default     = 90
}

variable "logs_retention_days" {
  description = <<-EOT
    Days before a shipped container-log object is expired from S3. Shorter than
    uploads_retention_days on purpose: logs are read to debug something that just
    happened — observability-mcp caps a single lookback at 24 hours — so keeping
    months of them costs storage without answering a question anyone asks.
  EOT
  type        = number
  default     = 14
}

# --- DynamoDB durability ---------------------------------------------------

variable "point_in_time_recovery" {
  description = <<-EOT
    Enable DynamoDB point-in-time recovery on all three tables. Off by default:
    PITR bills for continuous backups, and this is a course project whose data can
    be regenerated by re-uploading material. Turn it on if a demo's review history
    becomes worth protecting.
  EOT
  type        = bool
  default     = false
}

# ===========================================================================
# Cluster — VPC and the kubeadm-on-EC2 Kubernetes cluster
# ===========================================================================
#
# Everything below drives module "vpc" and module "k8s_cluster" in main.tf.
# `ssh_key_name` is the only one with no default: it names an EC2 key pair that
# must already exist in the region, and a wrong guess produces an instance nobody
# can log into — and since bootstrap.sh runs over SSH, a cluster nobody can finish
# building.

variable "vpc_cidr" {
  description = <<-EOT
    CIDR for the cluster VPC. Public subnets are derived from it with cidrsubnet(),
    so this is the only network number to change. Must not overlap
    `pod_network_cidr` — pod IPs and node IPs sharing a range breaks routing in ways
    that look like random pod-to-pod timeouts.
  EOT
  type        = string
  default     = "10.0.0.0/16"
}

variable "control_plane_instance_type" {
  description = <<-EOT
    Instance type for the control plane. t3.medium (2 vCPU / 4 GiB) is the practical
    floor: `kubeadm init` itself refuses to run with fewer than 2 CPUs, and etcd plus
    the API server leave little of 4 GiB spare.
  EOT
  type        = string
  default     = "t3.medium"
}

variable "worker_instance_type" {
  description = <<-EOT
    Instance type for worker nodes. t3.medium fits Recall's four workloads per env
    (frontend, tutor-agent, study-mcp, reminder CronJob) with room for Calico, the
    EBS CSI node plugin, and kube-proxy. t3.small (2 GiB) leaves too little once
    both dev and prod namespaces are running.
  EOT
  type        = string
  default     = "t3.medium"
}

variable "worker_desired_capacity" {
  description = <<-EOT
    Number of worker nodes the ASG runs. 1 is enough for dev+prod at demo scale and
    halves the hourly bill versus 2.

    Set to 0 to park the cluster without destroying it — the control plane keeps
    running (so the API server and its certificate survive) while the workers stop
    billing. Note this is NOT free: the control plane still bills, and the course
    budget-keeper Lambda will stop it at 16:00 anyway, which is unrecoverable. For a
    real overnight pause, `terraform destroy` is the correct move.
  EOT
  type        = number
  default     = 1

  validation {
    # Upper bound is worker_max_size' default of 3; the ASG rejects a desired
    # capacity above max_size at apply time, and catching it here gives a clearer
    # error than the AWS API's.
    condition     = var.worker_desired_capacity >= 0 && var.worker_desired_capacity <= 3
    error_message = "worker_desired_capacity must be between 0 and 3 (0 parks the workers; 3 is worker_max_size)."
  }
}

variable "root_volume_size" {
  description = <<-EOT
    Root EBS volume size in GiB for every node. 30 GiB, not the 8 GiB Ubuntu
    default: container images are the space hog here — the kubeadm control-plane
    images, Calico, and Recall's own three images (the Next.js frontend alone is
    several hundred MB) fill 8 GiB fast, and a full disk makes the kubelet start
    evicting pods with DiskPressure rather than failing loudly.
  EOT
  type        = number
  default     = 30
}

variable "kubernetes_version" {
  description = <<-EOT
    Kubernetes MINOR version, e.g. "1.30" — not a patch version. It selects the
    pkgs.k8s.io apt repository (core:/stable:/v1.30) in both user-data scripts, and
    those repositories are published per minor line. A patch-level string like
    "1.30.4" makes the apt source 404 and the boot fails.
  EOT
  type        = string
  default     = "v1.30"

  validation {
    condition     = can(regex("^v[0-9]+\\.[0-9]+$", var.kubernetes_version))
    error_message = "kubernetes_version must be a minor version prefixed with v, e.g. \"v1.30\" — pkgs.k8s.io has no per-patch repository."
  }
}

variable "pod_network_cidr" {
  description = <<-EOT
    CIDR that Calico allocates pod IPs from. 192.168.0.0/16 is Calico's own default
    and deliberately does not overlap `vpc_cidr` (10.0.0.0/16). Changing it means
    changing it in infra/k8s/bootstrap.sh too — the value passed to `kubeadm init`
    and the value in Calico's Installation resource must agree, and a mismatch
    produces nodes that stay NotReady with no obvious error.
  EOT
  type        = string
  default     = "192.168.0.0/16"
}

variable "ssh_key_name" {
  description = <<-EOT
    Name of an EXISTING EC2 key pair in this region, e.g. "shahd-key". Terraform
    does not create it: the private half would land in state, and state is not a
    secret store. Create one with

      aws ec2 create-key-pair --key-name shahd-key \
        --query KeyMaterial --output text > ~/.ssh/shahd-key.pem
      chmod 400 ~/.ssh/shahd-key.pem

    No default on purpose — a wrong name yields nodes nobody can SSH into, and
    bootstrap.sh (which installs the CNI) runs over SSH.
  EOT
  type        = string
}

variable "ssh_private_key_path" {
  description = <<-EOT
    Local path to the private key matching `ssh_key_name`. Terraform never reads this
    file; it exists only so the `ssh_command` / `fetch_kubeconfig_command` outputs
    can print a command you can paste. Verify the pair matches before applying:

      ssh-keygen -y -f ~/.ssh/shahd-key.pem
      aws ec2 describe-key-pairs --key-names shahd-key --include-public-key \
        --query 'KeyPairs[0].PublicKey' --output text
  EOT
  type        = string
  default     = "~/.ssh/shahd-key.pem"
}

# ===========================================================================
# Ingress — public DNS, TLS, and the load balancer
# ===========================================================================

variable "base_domain" {
  description = <<-EOT
    The SHARED Route 53 hosted zone, read with a data source and never managed by
    this stack. Every student in the account has records in it, so declaring it as a
    resource would let `terraform destroy` delete everyone's.
  EOT
  type        = string
  default     = "fursa.click"
}

variable "subdomain" {
  description = <<-EOT
    Recall's label under `base_domain`, giving the domain root recall.fursa.click.

    Deliberately NOT the student name: the reference project in this same account
    and hosted zone uses that, and sharing it would mean whichever stack applied
    second repointed the other's DNS at its own load balancer, with both ACM
    certificates competing over identical validation records.
  EOT
  type        = string
  default     = "recall"
}

variable "ingress_http_node_port" {
  description = <<-EOT
    NodePort the ingress-nginx controller is pinned to, and the port the ALB target
    group forwards to. Must match `controller.service.nodePorts.http` in
    infra/k8s/ingress-nginx/values.yaml — bootstrap.sh asserts it.

    Note this is OUTSIDE the app's own 30300-30800 / 31300-31800 ranges, so the
    worker security group gets a dedicated ALB-sourced rule for it (see
    modules/ingress). Without that rule every hostname returns 503.
  EOT
  type        = number
  default     = 30080
}

variable "alert_email" {
  description = <<-EOT
    Where Alertmanager's alerts are emailed, via SNS. Leave empty to create the topic
    without a subscriber — alerts still publish, they just reach nobody until someone
    subscribes.

    AWS emails a confirmation link the first time this is applied and delivers
    nothing until it is clicked. Terraform reports the subscription as created
    regardless, so `PendingConfirmation` is what to check when alerts fire but no
    mail arrives.
  EOT
  type        = string
  default     = ""
}

variable "ssh_ingress_cidr" {
  description = <<-EOT
    Source CIDR allowed to reach SSH (22) and the Kubernetes API (6443).

    Defaults to 0.0.0.0/0, which is a real exposure and a deliberate trade: the
    course network hands out changing addresses, and a stale CIDR here locks you out
    of a cluster whose CNI is not installed yet — unrecoverable without a destroy.
    The API server still requires client certificates and SSH still requires the key
    pair, so neither port is open in the sense of unauthenticated.

    Narrow it if your address is stable:  ssh_ingress_cidr = "203.0.113.4/32"
    (find it with `curl -s https://checkip.amazonaws.com`).

    NOTE this does NOT gate the NodePorts. Those are 0.0.0.0/0 unconditionally in
    the cluster module, because the demo is opened from a browser that is not
    necessarily on this address.
  EOT
  type        = string
  default     = "0.0.0.0/0"
}
